"""
Curation spec for the offline catalog builder.

Philosophy (Josh's standard): **curate the canon first, then resolve to a verified public-domain
image** — start from an opinionated "top works of all time" list, not from whatever an API search
returns. Each collection lists explicit `picks` (the must-see canon); the builder resolves each to a
PD image via the best source and verifies it's a real display image. Some famous works are still
under copyright and simply won't resolve to a PD source — that's expected; they're logged as MISSING.

Per-collection keys:
  - picks: [{title, artist?, sources?}]   the curated canon (resolved + verified)
  - pick_sources: resolver order for picks (default ["wikimedia", "museums"])
  - sources: museum ids for the resolver + query supplement; "nasa"/"loc" for those fetchers
  - queries / query_supplement: optional keyword-discovery top-up. **OPT-IN (default OFF)** — set
    query_supplement=True to enable. It's off by default because loose keyword search cross-contaminates
    collections (artist-name collisions like "Thomas"/"Turner"/"Gustave", broad theme queries pull
    off-topic works); the CURATION-v2 audit found ~104 mis-filed works from it. Curated picks are the
    source of truth.
  - target: cap on items.

Resolver ids: museum ids "chicago"/"met"/"cleveland"/"rijks"/"smk", plus "wikimedia", "nasa",
"loc" (Library of Congress digitized assets) and "smithsonian" (Smithsonian Open Access, CC0 only).
Modern works under copyright (most 20th-c art) remain intentionally absent — they won't resolve PD.
"""

COLLECTIONS = [
    {
        "id": "impressionism",
        "title": "Impressionism",
        "description": "Light, color, and fleeting moments from the movement that broke with the academy.",
        "license": "Public Domain",
        "sources": ["chicago", "met", "cleveland"],
        "pick_sources": ["wikimedia", "museums"],
        "queries": ["Claude Monet", "Pierre-Auguste Renoir", "Edgar Degas", "Camille Pissarro"],
        "target": 40,
        "picks": [
            {"title": "Impression, Sunrise", "artist": "Claude Monet"},
            {"title": "Water Lilies", "artist": "Claude Monet"},
            {"title": "Woman with a Parasol", "artist": "Claude Monet"},
            {"title": "Rouen Cathedral, West Facade, Sunlight", "artist": "Claude Monet"},
            {"title": "The Japanese Footbridge", "artist": "Claude Monet"},
            {"title": "Haystacks (End of Summer)", "artist": "Claude Monet"},
            {"title": "Poppies", "artist": "Claude Monet"},
            {"title": "The Gare Saint-Lazare", "artist": "Claude Monet"},
            {"title": "Wheatstacks (Snow Effect, Morning)", "artist": "Claude Monet"},
            {"title": "Dance at Le Moulin de la Galette", "artist": "Pierre-Auguste Renoir"},
            {"title": "Luncheon of the Boating Party", "artist": "Pierre-Auguste Renoir"},
            {"title": "Two Sisters (On the Terrace)", "artist": "Pierre-Auguste Renoir"},
            {"title": "Girls at the Piano", "artist": "Pierre-Auguste Renoir"},
            {"title": "The Swing", "artist": "Pierre-Auguste Renoir"},
            {"title": "The Ballet Class", "artist": "Edgar Degas"},
            {"title": "L'Absinthe", "artist": "Edgar Degas"},
            {"title": "The Star (Dancer on Stage)", "artist": "Edgar Degas"},
            {"title": "The Dance Class", "artist": "Edgar Degas"},
            {"title": "Place de la Concorde", "artist": "Edgar Degas"},
            {"title": "The Tub", "artist": "Edgar Degas"},
            {"title": "Boulevard Montmartre", "artist": "Camille Pissarro"},
            {"title": "Red Roofs, Corner of a Village, Winter", "artist": "Camille Pissarro"},
            {"title": "A Bar at the Folies-Bergère", "artist": "Édouard Manet"},
            {"title": "Boating", "artist": "Édouard Manet"},
            {"title": "The Railway", "artist": "Édouard Manet"},
            {"title": "Olympia", "artist": "Édouard Manet"},
            {"title": "The Cradle", "artist": "Berthe Morisot"},
            {"title": "The Harbor at Lorient", "artist": "Berthe Morisot"},
            {"title": "Summer's Day", "artist": "Berthe Morisot"},
            {"title": "The Boating Party", "artist": "Mary Cassatt"},
            {"title": "The Child's Bath", "artist": "Mary Cassatt"},
            {"title": "Paris Street; Rainy Day", "artist": "Gustave Caillebotte"},
            {"title": "The Floor Scrapers", "artist": "Gustave Caillebotte"},
            {"title": "The Bridge at Villeneuve-la-Garenne", "artist": "Alfred Sisley"},
            {"title": "Snow at Louveciennes", "artist": "Alfred Sisley"},
        ],
    },
    {
        "id": "post-impressionism",
        "title": "Post-Impressionism",
        "description": "Bold color and expressive form — the bridge from Impressionism to modern art.",
        "license": "Public Domain",
        "sources": ["chicago", "met", "rijks"],
        "pick_sources": ["wikimedia", "museums"],
        "queries": ["Vincent van Gogh", "Paul Cezanne", "Georges Seurat"],
        "target": 40,
        "picks": [
            {"title": "The Starry Night", "artist": "Vincent van Gogh"},
            {"title": "Sunflowers", "artist": "Vincent van Gogh"},
            {"title": "Café Terrace at Night", "artist": "Vincent van Gogh"},
            {"title": "The Bedroom", "artist": "Vincent van Gogh"},
            {"title": "Starry Night Over the Rhône", "artist": "Vincent van Gogh"},
            {"title": "Wheatfield with Crows", "artist": "Vincent van Gogh"},
            {"title": "Self-Portrait", "artist": "Vincent van Gogh"},
            {"title": "The Potato Eaters", "artist": "Vincent van Gogh"},
            {"title": "Irises", "artist": "Vincent van Gogh"},
            {"title": "Almond Blossom", "artist": "Vincent van Gogh"},
            {"title": "The Yellow House", "artist": "Vincent van Gogh"},
            {"title": "The Card Players", "artist": "Paul Cézanne"},
            {"title": "Mont Sainte-Victoire", "artist": "Paul Cézanne"},
            {"title": "The Large Bathers", "artist": "Paul Cézanne"},
            {"title": "Still Life with Apples and Oranges", "artist": "Paul Cézanne"},
            {"title": "The Boy in the Red Vest", "artist": "Paul Cézanne"},
            {"title": "Where Do We Come From? What Are We? Where Are We Going?", "artist": "Paul Gauguin"},
            {"title": "Vision after the Sermon", "artist": "Paul Gauguin"},
            {"title": "Tahitian Women on the Beach", "artist": "Paul Gauguin"},
            {"title": "The Yellow Christ", "artist": "Paul Gauguin"},
            {"title": "Spirit of the Dead Watching", "artist": "Paul Gauguin"},
            {"title": "Nevermore", "artist": "Paul Gauguin"},
            {"title": "A Sunday on La Grande Jatte", "artist": "Georges Seurat"},
            {"title": "Bathers at Asnières", "artist": "Georges Seurat"},
            {"title": "The Circus", "artist": "Georges Seurat"},
            {"title": "At the Moulin Rouge", "artist": "Henri de Toulouse-Lautrec"},
            {"title": "The Port of Saint-Tropez", "artist": "Paul Signac"},
            {"title": "The Sleeping Gypsy", "artist": "Henri Rousseau"},
        ],
    },
    {
        "id": "dutch-golden-age",
        "title": "The Dutch Golden Age",
        "description": "Light, intimacy, and virtuosity from the 17th-century Netherlands.",
        "license": "Public Domain",
        "sources": ["rijks", "met"],
        "pick_sources": ["wikimedia", "museums"],
        "queries": ["Rembrandt van Rijn", "Johannes Vermeer", "Frans Hals"],
        "target": 36,
        "picks": [
            {"title": "The Night Watch", "artist": "Rembrandt van Rijn"},
            {"title": "The Anatomy Lesson of Dr. Nicolaes Tulp", "artist": "Rembrandt van Rijn"},
            {"title": "Self-Portrait with Two Circles", "artist": "Rembrandt van Rijn"},
            {"title": "The Jewish Bride", "artist": "Rembrandt van Rijn"},
            {"title": "Syndics of the Drapers' Guild", "artist": "Rembrandt van Rijn"},
            {"title": "Belshazzar's Feast", "artist": "Rembrandt van Rijn"},
            {"title": "Bathsheba at Her Bath", "artist": "Rembrandt van Rijn"},
            {"title": "Aristotle with a Bust of Homer", "artist": "Rembrandt van Rijn"},
            {"title": "Girl with a Pearl Earring", "artist": "Johannes Vermeer"},
            {"title": "The Milkmaid", "artist": "Johannes Vermeer"},
            {"title": "View of Delft", "artist": "Johannes Vermeer"},
            {"title": "Woman Holding a Balance", "artist": "Johannes Vermeer"},
            {"title": "The Art of Painting", "artist": "Johannes Vermeer"},
            {"title": "Girl with a Red Hat", "artist": "Johannes Vermeer"},
            {"title": "The Little Street", "artist": "Johannes Vermeer"},
            {"title": "Woman Reading a Letter", "artist": "Johannes Vermeer"},
            {"title": "The Laughing Cavalier", "artist": "Frans Hals"},
            {"title": "The Merry Drinker", "artist": "Frans Hals"},
            {"title": "Malle Babbe", "artist": "Frans Hals"},
            {"title": "The Windmill at Wijk bij Duurstede", "artist": "Jacob van Ruisdael"},
            {"title": "View of Haarlem with Bleaching Grounds", "artist": "Jacob van Ruisdael"},
            {"title": "The Avenue at Middelharnis", "artist": "Meindert Hobbema"},
            {"title": "The Feast of Saint Nicholas", "artist": "Jan Steen"},
            {"title": "The Merry Family", "artist": "Jan Steen"},
            {"title": "The Courtyard of a House in Delft", "artist": "Pieter de Hooch"},
            {"title": "Still Life with a Gilt Cup", "artist": "Willem Claesz Heda"},
            {"title": "The Goldfinch", "artist": "Carel Fabritius"},
            {"title": "River Landscape with Riders", "artist": "Aelbert Cuyp"},
            {"title": "The Threatened Swan", "artist": "Jan Asselijn"},
        ],
    },
    {
        "id": "renaissance",
        "title": "The Italian Renaissance",
        "description": "Harmony, perspective, and humanism from the rebirth of classical ideals.",
        "license": "Public Domain",
        "sources": ["met", "chicago"],
        "pick_sources": ["wikimedia", "museums"],
        "queries": ["Sandro Botticelli", "Titian", "Renaissance Italian painting"],
        "target": 36,
        "picks": [
            {"title": "Mona Lisa", "artist": "Leonardo da Vinci"},
            {"title": "The Last Supper", "artist": "Leonardo da Vinci"},
            {"title": "Lady with an Ermine", "artist": "Leonardo da Vinci"},
            {"title": "Virgin of the Rocks", "artist": "Leonardo da Vinci"},
            {"title": "The Annunciation", "artist": "Leonardo da Vinci"},
            {"title": "Vitruvian Man", "artist": "Leonardo da Vinci"},
            {"title": "The Birth of Venus", "artist": "Sandro Botticelli"},
            {"title": "Primavera", "artist": "Sandro Botticelli"},
            {"title": "The Adoration of the Magi", "artist": "Sandro Botticelli"},
            {"title": "Pallas and the Centaur", "artist": "Sandro Botticelli"},
            {"title": "The School of Athens", "artist": "Raphael"},
            {"title": "Sistine Madonna", "artist": "Raphael"},
            {"title": "The Transfiguration", "artist": "Raphael"},
            {"title": "Portrait of Baldassare Castiglione", "artist": "Raphael"},
            {"title": "The Madonna of the Meadow", "artist": "Raphael"},
            {"title": "The Creation of Adam", "artist": "Michelangelo"},
            {"title": "The Last Judgment", "artist": "Michelangelo"},
            {"title": "Doni Tondo", "artist": "Michelangelo"},
            {"title": "Venus of Urbino", "artist": "Titian"},
            {"title": "Bacchus and Ariadne", "artist": "Titian"},
            {"title": "Assumption of the Virgin", "artist": "Titian"},
            {"title": "The Tribute Money", "artist": "Masaccio"},
            {"title": "The Tempest", "artist": "Giorgione"},
            {"title": "Sleeping Venus", "artist": "Giorgione"},
            {"title": "The Garden of Earthly Delights", "artist": "Hieronymus Bosch"},
            {"title": "The Hunters in the Snow", "artist": "Pieter Bruegel the Elder"},
            {"title": "The Ambassadors", "artist": "Hans Holbein the Younger"},
            {"title": "Self-Portrait (1500)", "artist": "Albrecht Dürer"},
            {"title": "Melencolia I", "artist": "Albrecht Dürer"},
        ],
    },
    {
        "id": "ukiyo-e",
        "title": "Japanese Ukiyo-e",
        "description": "Woodblock prints of the 'floating world' — landscapes, kabuki, and everyday Edo life.",
        "license": "Public Domain",
        "sources": ["chicago", "met", "smk"],
        "pick_sources": ["wikimedia", "museums"],
        "queries": ["Katsushika Hokusai", "Utagawa Hiroshige", "Kitagawa Utamaro"],
        "target": 40,
        "picks": [
            {"title": "The Great Wave off Kanagawa", "artist": "Katsushika Hokusai"},
            {"title": "Fine Wind, Clear Morning", "artist": "Katsushika Hokusai"},
            {"title": "Kajikazawa in Kai Province", "artist": "Katsushika Hokusai"},
            {"title": "Tea House at Koishikawa, the Morning After Snow", "artist": "Katsushika Hokusai"},
            {"title": "Mishima Pass in Kai Province", "artist": "Katsushika Hokusai"},
            {"title": "Ejiri in Suruga Province", "artist": "Katsushika Hokusai"},
            {"title": "Lake Suwa in Shinano Province", "artist": "Katsushika Hokusai"},
            {"title": "Plum Park in Kameido", "artist": "Utagawa Hiroshige"},
            {"title": "Sudden Shower over Shin-Ōhashi Bridge and Atake", "artist": "Utagawa Hiroshige"},
            {"title": "Asakusa Ricefields and Torinomachi Festival", "artist": "Utagawa Hiroshige"},
            {"title": "Horikiri Iris Garden", "artist": "Utagawa Hiroshige"},
            {"title": "Kanbara, Night Snow", "artist": "Utagawa Hiroshige"},
            {"title": "Shono, Driving Rain", "artist": "Utagawa Hiroshige"},
            {"title": "Nihonbashi, Morning Scene", "artist": "Utagawa Hiroshige"},
            {"title": "Moon Pine, Ueno", "artist": "Utagawa Hiroshige"},
            {"title": "Three Beauties of the Present Day", "artist": "Kitagawa Utamaro"},
            {"title": "Naniwaya Okita", "artist": "Kitagawa Utamaro"},
            {"title": "Woman Wiping Sweat", "artist": "Kitagawa Utamaro"},
            {"title": "The Actor Otani Oniji III", "artist": "Tōshūsai Sharaku"},
            {"title": "The Actor Segawa Tomisaburo II", "artist": "Tōshūsai Sharaku"},
            {"title": "Takiyasha the Witch and the Skeleton Spectre", "artist": "Utagawa Kuniyoshi"},
            {"title": "Miyamoto Musashi and the Whale", "artist": "Utagawa Kuniyoshi"},
            {"title": "Cats Suggested as the Fifty-three Stations of the Tokaido", "artist": "Utagawa Kuniyoshi"},
            {"title": "Beauty Combing Her Hair", "artist": "Utagawa Kunisada"},
            {"title": "The Courtesan Hanaogi", "artist": "Utagawa Toyokuni"},
        ],
    },
    {
        "id": "romanticism",
        "title": "Romanticism & the Sublime",
        "description": "Nature at its most awe-inspiring, and the human drama set against it.",
        "license": "Public Domain",
        "sources": ["met", "chicago", "cleveland"],
        "pick_sources": ["wikimedia", "museums"],
        "queries": ["Thomas Cole", "J. M. W. Turner"],
        "target": 36,
        "picks": [
            {"title": "Wanderer above the Sea of Fog", "artist": "Caspar David Friedrich"},
            {"title": "The Sea of Ice", "artist": "Caspar David Friedrich"},
            {"title": "Abbey in the Oakwood", "artist": "Caspar David Friedrich"},
            {"title": "Chalk Cliffs on Rügen", "artist": "Caspar David Friedrich"},
            {"title": "The Monk by the Sea", "artist": "Caspar David Friedrich"},
            {"title": "Liberty Leading the People", "artist": "Eugène Delacroix"},
            {"title": "The Death of Sardanapalus", "artist": "Eugène Delacroix"},
            {"title": "The Women of Algiers", "artist": "Eugène Delacroix"},
            {"title": "The Raft of the Medusa", "artist": "Théodore Géricault"},
            {"title": "The Fighting Temeraire", "artist": "J. M. W. Turner"},
            {"title": "Rain, Steam and Speed", "artist": "J. M. W. Turner"},
            {"title": "Snow Storm: Hannibal and His Army Crossing the Alps", "artist": "J. M. W. Turner"},
            {"title": "Ulysses Deriding Polyphemus", "artist": "J. M. W. Turner"},
            {"title": "Norham Castle, Sunrise", "artist": "J. M. W. Turner"},
            {"title": "The Hay Wain", "artist": "John Constable"},
            {"title": "Salisbury Cathedral from the Meadows", "artist": "John Constable"},
            {"title": "The Cornfield", "artist": "John Constable"},
            {"title": "Wivenhoe Park", "artist": "John Constable"},
            {"title": "The Oxbow", "artist": "Thomas Cole"},
            {"title": "The Course of Empire: Destruction", "artist": "Thomas Cole"},
            {"title": "The Voyage of Life: Childhood", "artist": "Thomas Cole"},
            {"title": "The Third of May 1808", "artist": "Francisco Goya"},
            {"title": "Saturn Devouring His Son", "artist": "Francisco Goya"},
            {"title": "The Naked Maja", "artist": "Francisco Goya"},
            {"title": "Witches' Sabbath (The Great He-Goat)", "artist": "Francisco Goya"},
            {"title": "The Nightmare", "artist": "Henry Fuseli"},
            {"title": "The Great Red Dragon and the Woman Clothed with the Sun", "artist": "William Blake"},
            {"title": "The Ancient of Days", "artist": "William Blake"},
            {"title": "Newton", "artist": "William Blake"},
            {"title": "Kindred Spirits", "artist": "Asher Brown Durand"},
        ],
    },
    {
        "id": "american-art",
        "title": "American Art",
        "description": "From frontier light to mid-century city scenes — the American eye.",
        "license": "Public Domain",
        "sources": ["chicago", "met", "cleveland"],
        "pick_sources": ["wikimedia", "museums"],
        "queries": ["Winslow Homer", "John Singer Sargent"],
        "target": 36,
        "picks": [
            {"title": "Nighthawks", "artist": "Edward Hopper"},
            {"title": "American Gothic", "artist": "Grant Wood"},
            {"title": "Arrangement in Grey and Black No. 1", "artist": "James McNeill Whistler"},
            {"title": "Washington Crossing the Delaware", "artist": "Emanuel Leutze"},
            {"title": "The Gulf Stream", "artist": "Winslow Homer"},
            {"title": "Snap the Whip", "artist": "Winslow Homer"},
            {"title": "Breezing Up (A Fair Wind)", "artist": "Winslow Homer"},
            {"title": "The Fog Warning", "artist": "Winslow Homer"},
            {"title": "The Veteran in a New Field", "artist": "Winslow Homer"},
            {"title": "Northeaster", "artist": "Winslow Homer"},
            {"title": "Madame X", "artist": "John Singer Sargent"},
            {"title": "The Daughters of Edward Darley Boit", "artist": "John Singer Sargent"},
            {"title": "Carnation, Lily, Lily, Rose", "artist": "John Singer Sargent"},
            {"title": "El Jaleo", "artist": "John Singer Sargent"},
            {"title": "Lady Agnew of Lochnaw", "artist": "John Singer Sargent"},
            {"title": "The Gross Clinic", "artist": "Thomas Eakins"},
            {"title": "Max Schmitt in a Single Scull", "artist": "Thomas Eakins"},
            {"title": "The Champion Single Sculls", "artist": "Thomas Eakins"},
            {"title": "Among the Sierra Nevada, California", "artist": "Albert Bierstadt"},
            {"title": "The Rocky Mountains, Lander's Peak", "artist": "Albert Bierstadt"},
            {"title": "The Heart of the Andes", "artist": "Frederic Edwin Church"},
            {"title": "Niagara", "artist": "Frederic Edwin Church"},
            {"title": "Twilight in the Wilderness", "artist": "Frederic Edwin Church"},
            {"title": "The Banjo Lesson", "artist": "Henry Ossawa Tanner"},
            {"title": "The Resurrection of Lazarus", "artist": "Henry Ossawa Tanner"},
            {"title": "A Dash for the Timber", "artist": "Frederic Remington"},
            {"title": "Fur Traders Descending the Missouri", "artist": "George Caleb Bingham"},
            {"title": "Watson and the Shark", "artist": "John Singleton Copley"},
            {"title": "The Lackawanna Valley", "artist": "George Inness"},
        ],
    },
    {
        "id": "portraits",
        "title": "Portraits Through Time",
        "description": "Faces that have held our gaze across the centuries.",
        "license": "Public Domain",
        "sources": ["met", "rijks", "chicago"],
        "pick_sources": ["wikimedia", "museums"],
        "queries": ["portrait painting"],
        "target": 36,
        "picks": [
            {"title": "The Arnolfini Portrait", "artist": "Jan van Eyck"},
            {"title": "Las Meninas", "artist": "Diego Velázquez"},
            {"title": "Portrait of Pope Innocent X", "artist": "Diego Velázquez"},
            {"title": "Juan de Pareja", "artist": "Diego Velázquez"},
            {"title": "The Blue Boy", "artist": "Thomas Gainsborough"},
            {"title": "Mr and Mrs Andrews", "artist": "Thomas Gainsborough"},
            {"title": "The Honourable Mrs Graham", "artist": "Thomas Gainsborough"},
            {"title": "Napoleon Crossing the Alps", "artist": "Jacques-Louis David"},
            {"title": "The Death of Marat", "artist": "Jacques-Louis David"},
            {"title": "Portrait of Madame Récamier", "artist": "Jacques-Louis David"},
            {"title": "Self-Portrait at Twenty-Eight", "artist": "Albrecht Dürer"},
            {"title": "Portrait of Dr. Gachet", "artist": "Vincent van Gogh"},
            {"title": "Self-Portrait with Bandaged Ear", "artist": "Vincent van Gogh"},
            {"title": "Lady with an Ermine", "artist": "Leonardo da Vinci"},
            {"title": "The Ambassadors", "artist": "Hans Holbein the Younger"},
            {"title": "Portrait of Henry VIII", "artist": "Hans Holbein the Younger"},
            {"title": "Portrait of Eleonora di Toledo", "artist": "Agnolo Bronzino"},
            {"title": "Portrait of Madame Moitessier", "artist": "Jean-Auguste-Dominique Ingres"},
            {"title": "Portrait of Madame de Senonnes", "artist": "Jean-Auguste-Dominique Ingres"},
            {"title": "Self-Portrait (1659)", "artist": "Rembrandt van Rijn"},
            {"title": "Self-Portrait with Beret and Turned-Up Collar", "artist": "Rembrandt van Rijn"},
            {"title": "Portrait of Pope Julius II", "artist": "Raphael"},
            {"title": "Portrait of a Young Man", "artist": "Sandro Botticelli"},
            {"title": "Charles I at the Hunt", "artist": "Anthony van Dyck"},
            {"title": "Equestrian Portrait of Charles I", "artist": "Anthony van Dyck"},
            {"title": "Charles IV of Spain and His Family", "artist": "Francisco Goya"},
            {"title": "The Clothed Maja", "artist": "Francisco Goya"},
            {"title": "Madame Cézanne in a Red Armchair", "artist": "Paul Cézanne"},
            {"title": "Portrait of Adele Bloch-Bauer I", "artist": "Gustav Klimt"},
        ],
    },
    {
        "id": "still-life",
        "title": "Still Life & Flowers",
        "description": "Quiet arrangements of fruit, flowers, and objects — beauty in the everyday.",
        "license": "Public Domain",
        "sources": ["rijks", "met", "chicago"],
        "pick_sources": ["wikimedia", "museums"],
        "queries": ["still life flowers", "vanitas"],
        "target": 36,
        "picks": [
            {"title": "Irises", "artist": "Vincent van Gogh"},
            {"title": "Vase with Twelve Sunflowers", "artist": "Vincent van Gogh"},
            {"title": "Still Life: Vase with Pink Roses", "artist": "Vincent van Gogh"},
            {"title": "The Basket of Apples", "artist": "Paul Cézanne"},
            {"title": "Still Life with Apples and Oranges", "artist": "Paul Cézanne"},
            {"title": "Still Life with a Curtain", "artist": "Paul Cézanne"},
            {"title": "Still Life with Plaster Cupid", "artist": "Paul Cézanne"},
            {"title": "The Ray", "artist": "Jean-Siméon Chardin"},
            {"title": "Still Life with Glass Flask and Fruit", "artist": "Jean-Siméon Chardin"},
            {"title": "Basket of Fruit", "artist": "Caravaggio"},
            {"title": "Still Life with Flowers in a Glass Vase", "artist": "Jan Davidsz. de Heem"},
            {"title": "Festoon of Fruit and Flowers", "artist": "Jan Davidsz. de Heem"},
            {"title": "Flowers in a Wooden Vessel", "artist": "Jan Brueghel the Elder"},
            {"title": "A Vase of Flowers", "artist": "Rachel Ruysch"},
            {"title": "Still Life of Flowers", "artist": "Ambrosius Bosschaert the Elder"},
            {"title": "Still Life with a Gilt Cup", "artist": "Willem Claesz Heda"},
            {"title": "Still Life with a Lobster", "artist": "Willem Kalf"},
            {"title": "Vanitas Still Life", "artist": "Pieter Claesz"},
            {"title": "Still Life with a Skull", "artist": "Pieter Claesz"},
            {"title": "Banquet Still Life", "artist": "Adriaen van Utrecht"},
            {"title": "Still Life with Flowers and Fruit", "artist": "Henri Fantin-Latour"},
            {"title": "Roses", "artist": "Henri Fantin-Latour"},
            {"title": "Quince, Cabbage, Melon, and Cucumber", "artist": "Juan Sánchez Cotán"},
            {"title": "Still Life with Cake", "artist": "Raphaelle Peale"},
        ],
    },
    {
        "id": "sculpture-antiquity",
        "title": "Sculpture & Antiquity",
        "description": "Marble, bronze, and stone — the enduring forms of the ancient and classical world.",
        "license": "Public Domain",
        "sources": ["met", "cleveland"],
        "pick_sources": ["wikimedia", "museums"],
        "queries": ["marble sculpture", "Greek statue"],
        "target": 32,
        "picks": [
            {"title": "Venus de Milo", "artist": "Ancient Greek"},
            {"title": "Winged Victory of Samothrace", "artist": "Ancient Greek"},
            {"title": "Laocoön and His Sons", "artist": "Ancient Greek"},
            {"title": "David", "artist": "Michelangelo"},
            {"title": "Pietà", "artist": "Michelangelo"},
            {"title": "Moses", "artist": "Michelangelo"},
            {"title": "Discobolus", "artist": "Myron"},
            {"title": "Bust of Nefertiti", "artist": "Thutmose"},
            {"title": "The Thinker", "artist": "Auguste Rodin"},
            {"title": "The Kiss", "artist": "Auguste Rodin"},
            {"title": "The Burghers of Calais", "artist": "Auguste Rodin"},
            {"title": "Augustus of Prima Porta", "artist": "Ancient Roman"},
            {"title": "Apollo Belvedere", "artist": "Ancient Greek"},
            {"title": "The Dying Gaul", "artist": "Ancient Roman"},
            {"title": "Apollo and Daphne", "artist": "Gian Lorenzo Bernini"},
            {"title": "Ecstasy of Saint Teresa", "artist": "Gian Lorenzo Bernini"},
            {"title": "David", "artist": "Gian Lorenzo Bernini"},
            {"title": "The Rape of Proserpina", "artist": "Gian Lorenzo Bernini"},
            {"title": "David", "artist": "Donatello"},
            {"title": "Psyche Revived by Cupid's Kiss", "artist": "Antonio Canova"},
            {"title": "Perseus with the Head of Medusa", "artist": "Antonio Canova"},
            {"title": "Farnese Hercules", "artist": "Ancient Roman"},
            {"title": "Capitoline Venus", "artist": "Ancient Roman"},
            {"title": "Charioteer of Delphi", "artist": "Ancient Greek"},
            {"title": "Artemision Bronze", "artist": "Ancient Greek"},
            {"title": "Riace Bronzes", "artist": "Ancient Greek"},
            {"title": "The Rape of the Sabine Women", "artist": "Giambologna"},
            {"title": "Perseus with the Head of Medusa", "artist": "Benvenuto Cellini"},
            {"title": "Barberini Faun", "artist": "Ancient Greek"},
        ],
    },
    {
        "id": "botanical",
        "title": "Birds & Botanicals",
        "description": "The art of scientific observation — Audubon's birds and the great botanical plates.",
        "license": "Public Domain",
        "sources": ["chicago", "met"],
        "pick_sources": ["wikimedia", "museums"],
        "queries": ["John James Audubon"],
        "target": 36,
        "picks": [
            {"title": "American Flamingo", "artist": "John James Audubon"},
            {"title": "Wild Turkey", "artist": "John James Audubon"},
            {"title": "Snowy Owl", "artist": "John James Audubon"},
            {"title": "Carolina Parakeet", "artist": "John James Audubon"},
            {"title": "Whooping Crane", "artist": "John James Audubon"},
            {"title": "Great Blue Heron", "artist": "John James Audubon"},
            {"title": "Roseate Spoonbill", "artist": "John James Audubon"},
            {"title": "Ivory-billed Woodpecker", "artist": "John James Audubon"},
            {"title": "Northern Cardinal", "artist": "John James Audubon"},
            {"title": "Blue Jay", "artist": "John James Audubon"},
            {"title": "Bald Eagle", "artist": "John James Audubon"},
            {"title": "Trumpeter Swan", "artist": "John James Audubon"},
            {"title": "Passenger Pigeon", "artist": "John James Audubon"},
            {"title": "Common Loon", "artist": "John James Audubon"},
            {"title": "Rosa centifolia", "artist": "Pierre-Joseph Redouté"},
            {"title": "Strelitzia reginae", "artist": "Pierre-Joseph Redouté"},
            {"title": "Rosa gallica", "artist": "Pierre-Joseph Redouté"},
            {"title": "Amaryllis", "artist": "Pierre-Joseph Redouté"},
            {"title": "Discomedusae", "artist": "Ernst Haeckel"},
            {"title": "Actiniae", "artist": "Ernst Haeckel"},
            {"title": "Trochilidae", "artist": "Ernst Haeckel"},
            {"title": "Orchidae", "artist": "Ernst Haeckel"},
            {"title": "Radiolaria", "artist": "Ernst Haeckel"},
            {"title": "Metamorphosis of a Pineapple", "artist": "Maria Sibylla Merian"},
            {"title": "Branch of Pomelo with Moth", "artist": "Maria Sibylla Merian"},
            {"title": "Iris", "artist": "Basilius Besler"},
            {"title": "Fritillaria", "artist": "Basilius Besler"},
            {"title": "Magnolia", "artist": "Mark Catesby"},
        ],
    },
    {
        "id": "modern-masters",
        "title": "Modern Masters",
        "description": "The turn into modernism — symbolism and expression at the dawn of the new century.",
        "license": "Public Domain",
        "sources": ["met", "chicago", "smk"],
        "pick_sources": ["wikimedia", "museums"],
        "queries": ["Gustav Klimt", "Edvard Munch"],
        "target": 30,
        "picks": [
            {"title": "The Kiss", "artist": "Gustav Klimt"},
            {"title": "Portrait of Adele Bloch-Bauer I", "artist": "Gustav Klimt"},
            {"title": "Death and Life", "artist": "Gustav Klimt"},
            {"title": "Judith and the Head of Holofernes", "artist": "Gustav Klimt"},
            {"title": "The Beethoven Frieze", "artist": "Gustav Klimt"},
            {"title": "Portrait of Adele Bloch-Bauer II", "artist": "Gustav Klimt"},
            {"title": "Hope II", "artist": "Gustav Klimt"},
            {"title": "Danaë", "artist": "Gustav Klimt"},
            {"title": "The Virgin", "artist": "Gustav Klimt"},
            {"title": "The Scream", "artist": "Edvard Munch"},
            {"title": "Madonna", "artist": "Edvard Munch"},
            {"title": "The Sick Child", "artist": "Edvard Munch"},
            {"title": "The Dance of Life", "artist": "Edvard Munch"},
            {"title": "Vampire", "artist": "Edvard Munch"},
            {"title": "Anxiety", "artist": "Edvard Munch"},
            {"title": "Ashes", "artist": "Edvard Munch"},
            {"title": "Puberty", "artist": "Edvard Munch"},
            {"title": "Self-Portrait with Burning Cigarette", "artist": "Edvard Munch"},
            {"title": "Death in the Sickroom", "artist": "Edvard Munch"},
            {"title": "Seated Woman with Bent Knee", "artist": "Egon Schiele"},
            {"title": "Death and the Maiden", "artist": "Egon Schiele"},
            {"title": "The Embrace", "artist": "Egon Schiele"},
            {"title": "Cardinal and Nun (Caress)", "artist": "Egon Schiele"},
            {"title": "The Cyclops", "artist": "Odilon Redon"},
            {"title": "Oedipus and the Sphinx", "artist": "Gustave Moreau"},
            {"title": "Isle of the Dead", "artist": "Arnold Böcklin"},
            {"title": "The Night", "artist": "Ferdinand Hodler"},
        ],
    },
    {
        "id": "cosmos",
        "title": "The Cosmos",
        "description": "Public-domain views of deep space from Hubble and the James Webb Space Telescope.",
        "license": "Public Domain (NASA / ESA)",
        "sources": ["nasa"],
        "pick_sources": ["wikimedia", "nasa"],
        "queries": [],
        "query_supplement": False,
        "target": 26,
        "picks": [
            {"title": "Pillars of Creation"},
            {"title": "Webb's First Deep Field"},
            {"title": "Cosmic Cliffs Carina Nebula"},
            {"title": "Hubble Ultra Deep Field"},
            {"title": "Sombrero Galaxy"},
            {"title": "Whirlpool Galaxy"},
            {"title": "Crab Nebula"},
            {"title": "Horsehead Nebula"},
            {"title": "Andromeda Galaxy"},
            {"title": "Veil Nebula"},
            {"title": "Southern Ring Nebula Webb"},
            {"title": "Stephan's Quintet Webb"},
            {"title": "Eagle Nebula"},
            {"title": "Tarantula Nebula Webb"},
            {"title": "Helix Nebula"},
            {"title": "Cat's Eye Nebula"},
            {"title": "Ring Nebula"},
            {"title": "Orion Nebula"},
            {"title": "Pinwheel Galaxy"},
            {"title": "Antennae Galaxies"},
            {"title": "Hubble Deep Field"},
            {"title": "Mystic Mountain"},
            {"title": "Butterfly Nebula NGC 6302"},
            {"title": "Cartwheel Galaxy Webb"},
            {"title": "Phantom Galaxy"},
            {"title": "Cosmic Reef"},
        ],
    },
    {
        "id": "earth-and-spaceflight",
        "title": "Earth & Spaceflight",
        "description": "Our planet and the missions that let us see it — from Apollo to deep space.",
        "license": "Public Domain (NASA)",
        "sources": ["nasa"],
        "pick_sources": ["wikimedia", "nasa"],
        "queries": [],
        "query_supplement": False,
        "target": 22,
        "picks": [
            {"title": "The Blue Marble"},
            {"title": "Earthrise"},
            {"title": "Pale Blue Dot"},
            {"title": "Buzz Aldrin on the Moon Apollo 11"},
            {"title": "Bruce McCandless spacewalk"},
            {"title": "Saturn from Cassini"},
            {"title": "The Earth seen from Apollo 17"},
            {"title": "Apollo 11 bootprint on the Moon"},
            {"title": "Blue Marble 2012"},
            {"title": "The Day the Earth Smiled"},
            {"title": "Apollo 8 Crew Portrait"},
            {"title": "Apollo 11 Lunar Module Eagle"},
            {"title": "Eugene Cernan on the Moon"},
            {"title": "Curiosity Self-Portrait at Mars"},
            {"title": "Perseverance Selfie with Ingenuity"},
            {"title": "Valles Marineris"},
            {"title": "Pluto New Horizons"},
            {"title": "Jupiter's Great Red Spot Juno"},
            {"title": "Voyager Family Portrait"},
            {"title": "Hubble Space Telescope in Orbit"},
        ],
    },
    {
        "id": "vintage-posters",
        "title": "Vintage Posters & Graphic Design",
        "description": "Public-domain poster art — Art Nouveau, Belle Époque, and golden-age design.",
        "license": "Public Domain",
        "sources": ["wikimedia"],
        "pick_sources": ["wikimedia"],
        "queries": [],
        "query_supplement": False,
        "target": 36,
        "picks": [
            {"title": "Moulin Rouge: La Goulue", "artist": "Henri de Toulouse-Lautrec"},
            {"title": "Divan Japonais", "artist": "Henri de Toulouse-Lautrec"},
            {"title": "Aristide Bruant dans son cabaret", "artist": "Henri de Toulouse-Lautrec"},
            {"title": "Jane Avril", "artist": "Henri de Toulouse-Lautrec"},
            {"title": "Reine de Joie", "artist": "Henri de Toulouse-Lautrec"},
            {"title": "La Revue Blanche", "artist": "Henri de Toulouse-Lautrec"},
            {"title": "May Belfort", "artist": "Henri de Toulouse-Lautrec"},
            {"title": "Gismonda", "artist": "Alphonse Mucha"},
            {"title": "Job", "artist": "Alphonse Mucha"},
            {"title": "Bières de la Meuse", "artist": "Alphonse Mucha"},
            {"title": "F. Champenois Imprimeur-Éditeur", "artist": "Alphonse Mucha"},
            {"title": "Zodiac", "artist": "Alphonse Mucha"},
            {"title": "Rêverie", "artist": "Alphonse Mucha"},
            {"title": "The Seasons: Spring", "artist": "Alphonse Mucha"},
            {"title": "The Seasons: Autumn", "artist": "Alphonse Mucha"},
            {"title": "The Arts: Dance", "artist": "Alphonse Mucha"},
            {"title": "La Dame aux Camélias", "artist": "Alphonse Mucha"},
            {"title": "Monaco Monte-Carlo", "artist": "Alphonse Mucha"},
            {"title": "Le Chat Noir", "artist": "Théophile Steinlen"},
            {"title": "Folies Bergère", "artist": "Jules Chéret"},
            {"title": "Folies-Bergère, La Loïe Fuller", "artist": "Jules Chéret"},
            {"title": "Bal du Moulin Rouge", "artist": "Jules Chéret"},
            {"title": "Salon des Cent", "artist": "Eugène Grasset"},
            {"title": "Absinthe Robette", "artist": "Privat Livemont"},
            {"title": "Rajah Café", "artist": "Privat Livemont"},
            {"title": "Bitter Campari", "artist": "Leonetto Cappiello"},
            {"title": "Maurin Quina", "artist": "Leonetto Cappiello"},
            {"title": "Chocolat Klaus", "artist": "Leonetto Cappiello"},
            {"title": "See America Welcome to Montana", "artist": "WPA Federal Art Project", "sources": ["wikimedia"]},
            {"title": "Grand Canyon National Park", "artist": "WPA Federal Art Project", "sources": ["wikimedia"]},
            {"title": "Work Pays America WPA", "artist": "WPA Federal Art Project", "sources": ["wikimedia"]},
            {"title": "I Want You for U.S. Army", "artist": "James Montgomery Flagg", "sources": ["wikimedia"]},
            {"title": "Destroy This Mad Brute", "artist": "Harry R. Hopps", "sources": ["wikimedia"]},
            {"title": "When Hearts are Trumps", "artist": "Will H. Bradley"},
            {"title": "Harper's March", "artist": "Edward Penfield"},
            {"title": "The Boston Sunday Herald", "artist": "Ethel Reed"},
        ],
    },
    {
        "id": "documentary-photography",
        "title": "Documentary Photography",
        "description": "The unflinching photograph — the FSA archive and the pioneers of the form.",
        "license": "Public Domain",
        "sources": ["wikimedia"],
        "pick_sources": ["wikimedia"],
        "queries": [],
        "query_supplement": False,
        "target": 32,
        "picks": [
            {"title": "Migrant Mother", "artist": "Dorothea Lange"},
            {"title": "Ditched, Stalled, and Stranded", "artist": "Dorothea Lange"},
            {"title": "Toward Los Angeles", "artist": "Dorothea Lange"},
            {"title": "Tractored Out, Childress County Texas", "artist": "Dorothea Lange"},
            {"title": "The Steerage", "artist": "Alfred Stieglitz"},
            {"title": "Floyd Burroughs, cotton sharecropper", "artist": "Walker Evans"},
            {"title": "Roadside stand near Birmingham", "artist": "Walker Evans"},
            {"title": "Allie Mae Burroughs", "artist": "Walker Evans"},
            {"title": "Fleeing a Dust Storm", "artist": "Arthur Rothstein"},
            {"title": "American Gothic, Washington, D.C.", "artist": "Gordon Parks"},
            {"title": "Power house mechanic working on steam pump", "artist": "Lewis Hine"},
            {"title": "Breaker Boys, Pennsylvania", "artist": "Lewis Hine"},
            {"title": "Spinner in a Cotton Mill", "artist": "Lewis Hine"},
            {"title": "Bandit's Roost", "artist": "Jacob Riis"},
            {"title": "A Harvest of Death, Gettysburg", "artist": "Timothy H. O'Sullivan"},
            {"title": "Home of a Rebel Sharpshooter", "artist": "Alexander Gardner"},
            {"title": "The Dead of Antietam", "artist": "Alexander Gardner"},
            {"title": "Ancient Ruins in the Canyon de Chelly", "artist": "Timothy H. O'Sullivan"},
            {"title": "Cape Horn near Celilo", "artist": "Carleton Watkins"},
            {"title": "Yosemite Valley from Inspiration Point", "artist": "Carleton Watkins"},
            {"title": "Mountain of the Holy Cross", "artist": "William Henry Jackson"},
            {"title": "Grand Canyon of the Yellowstone", "artist": "William Henry Jackson"},
            {"title": "The Horse in Motion", "artist": "Eadweard Muybridge", "sources": ["wikimedia"]},
            {"title": "Boulevard du Temple", "artist": "Louis Daguerre", "sources": ["wikimedia"]},
            {"title": "The Open Door", "artist": "William Henry Fox Talbot", "sources": ["wikimedia"]},
            {"title": "View from the Window at Le Gras", "artist": "Nicéphore Niépce", "sources": ["wikimedia"]},
            {"title": "Geronimo", "artist": "Edward S. Curtis"},
            {"title": "Canyon de Chelly - Navaho", "artist": "Edward S. Curtis"},
        ],
    },
    # ------------------------------------------------------------------ new collections
    {
        "id": "baroque",
        "title": "Baroque & the Dramatic Light",
        "description": "The drama, movement, and shadow-pierced chiaroscuro of 17th-century Europe.",
        "license": "Public Domain",
        "sources": ["met", "chicago", "cleveland"],
        "pick_sources": ["wikimedia", "museums"],
        "queries": ["Caravaggio", "Peter Paul Rubens"],
        "query_supplement": False,
        "target": 28,
        "picks": [
            {"title": "The Calling of Saint Matthew", "artist": "Caravaggio"},
            {"title": "The Supper at Emmaus", "artist": "Caravaggio"},
            {"title": "The Conversion of Saint Paul on the Way to Damascus", "artist": "Caravaggio"},
            {"title": "Bacchus", "artist": "Caravaggio"},
            {"title": "Judith Beheading Holofernes", "artist": "Caravaggio"},
            {"title": "David with the Head of Goliath", "artist": "Caravaggio"},
            {"title": "Boy with a Basket of Fruit", "artist": "Caravaggio"},
            {"title": "The Cardsharps", "artist": "Caravaggio"},
            {"title": "Judith Slaying Holofernes", "artist": "Artemisia Gentileschi"},
            {"title": "Self-Portrait as the Allegory of Painting", "artist": "Artemisia Gentileschi"},
            {"title": "The Descent from the Cross", "artist": "Peter Paul Rubens"},
            {"title": "The Garden of Love", "artist": "Peter Paul Rubens"},
            {"title": "Samson and Delilah", "artist": "Peter Paul Rubens"},
            {"title": "The Three Graces", "artist": "Peter Paul Rubens"},
            {"title": "The Surrender of Breda", "artist": "Diego Velázquez"},
            {"title": "The Toilet of Venus (Rokeby Venus)", "artist": "Diego Velázquez"},
            {"title": "Old Woman Frying Eggs", "artist": "Diego Velázquez"},
            {"title": "The Storm on the Sea of Galilee", "artist": "Rembrandt van Rijn"},
            {"title": "The Penitent Magdalene", "artist": "Georges de La Tour"},
            {"title": "The Newborn Child", "artist": "Georges de La Tour"},
            {"title": "Saint Francis in Meditation", "artist": "Francisco de Zurbarán"},
            {"title": "Aurora", "artist": "Guido Reni"},
            {"title": "Et in Arcadia ego", "artist": "Nicolas Poussin"},
            {"title": "Seaport with the Embarkation of the Queen of Sheba", "artist": "Claude Lorrain"},
            {"title": "The Martyrdom of Saint Philip", "artist": "Jusepe de Ribera"},
            {"title": "The Immaculate Conception", "artist": "Bartolomé Esteban Murillo"},
        ],
    },
    {
        "id": "symbolism-romance",
        "title": "Symbolism & the Pre-Raphaelites",
        "description": "Dreamlike myth, doomed romance, and veiled mystery from the later 19th century.",
        "license": "Public Domain",
        "sources": ["met", "cleveland"],
        "pick_sources": ["wikimedia", "museums"],
        "queries": ["Pre-Raphaelite painting", "John William Waterhouse"],
        "query_supplement": False,
        "target": 28,
        "picks": [
            {"title": "Ophelia", "artist": "John Everett Millais"},
            {"title": "Christ in the House of His Parents", "artist": "John Everett Millais"},
            {"title": "Proserpine", "artist": "Dante Gabriel Rossetti"},
            {"title": "Beata Beatrix", "artist": "Dante Gabriel Rossetti"},
            {"title": "The Day Dream", "artist": "Dante Gabriel Rossetti"},
            {"title": "Lady Lilith", "artist": "Dante Gabriel Rossetti"},
            {"title": "The Light of the World", "artist": "William Holman Hunt"},
            {"title": "The Awakening Conscience", "artist": "William Holman Hunt"},
            {"title": "The Golden Stairs", "artist": "Edward Burne-Jones"},
            {"title": "The Beguiling of Merlin", "artist": "Edward Burne-Jones"},
            {"title": "King Cophetua and the Beggar Maid", "artist": "Edward Burne-Jones"},
            {"title": "The Lady of Shalott", "artist": "John William Waterhouse"},
            {"title": "Hylas and the Nymphs", "artist": "John William Waterhouse"},
            {"title": "Ophelia", "artist": "John William Waterhouse"},
            {"title": "The Magic Circle", "artist": "John William Waterhouse"},
            {"title": "Work", "artist": "Ford Madox Brown"},
            {"title": "The Last of England", "artist": "Ford Madox Brown"},
            {"title": "The Apparition", "artist": "Gustave Moreau"},
            {"title": "Jupiter and Semele", "artist": "Gustave Moreau"},
            {"title": "Oedipus and the Sphinx", "artist": "Gustave Moreau"},
            {"title": "The Cyclops", "artist": "Odilon Redon"},
            {"title": "Isle of the Dead", "artist": "Arnold Böcklin"},
            {"title": "The Poor Fisherman", "artist": "Pierre Puvis de Chavannes"},
            {"title": "I Lock My Door Upon Myself", "artist": "Fernand Khnopff"},
            {"title": "The Sin", "artist": "Franz von Stuck"},
            {"title": "Flaming June", "artist": "Frederic Leighton"},
            {"title": "The Roses of Heliogabalus", "artist": "Lawrence Alma-Tadema"},
        ],
    },
    {
        "id": "art-nouveau-decorative",
        "title": "Art Nouveau & the Decorative Arts",
        "description": "Sinuous line, gilded ornament, and the whiplash curve across print, glass, and design.",
        "license": "Public Domain",
        "sources": ["met", "chicago", "smk"],
        "pick_sources": ["wikimedia", "museums", "smithsonian"],
        "queries": [],
        "query_supplement": False,
        "target": 26,
        "picks": [
            {"title": "The Tree of Life (Stoclet Frieze)", "artist": "Gustav Klimt"},
            {"title": "Pallas Athene", "artist": "Gustav Klimt"},
            {"title": "Danaë", "artist": "Gustav Klimt"},
            {"title": "The Beethoven Frieze", "artist": "Gustav Klimt"},
            {"title": "The Slav Epic: The Apotheosis of the Slavs", "artist": "Alphonse Mucha"},
            {"title": "Documents Décoratifs", "artist": "Alphonse Mucha"},
            {"title": "Strawberry Thief", "artist": "William Morris"},
            {"title": "Trellis", "artist": "William Morris"},
            {"title": "Acanthus", "artist": "William Morris"},
            {"title": "Magnolia and Irises", "artist": "Tiffany Studios", "sources": ["museums", "wikimedia"]},
            {"title": "Wisteria Table Lamp", "artist": "Tiffany Studios"},
            {"title": "The Peacock Skirt", "artist": "Aubrey Beardsley"},
            {"title": "The Climax", "artist": "Aubrey Beardsley"},
            {"title": "The Dancer's Reward", "artist": "Aubrey Beardsley"},
            {"title": "Neptune's Horses", "artist": "Walter Crane"},
            {"title": "Swan, Rush and Iris", "artist": "Walter Crane"},
            {"title": "Grammar of Ornament: Moresque No. 1", "artist": "Owen Jones"},
            {"title": "Grammar of Ornament: Egyptian No. 1", "artist": "Owen Jones"},
            {"title": "Ver Sacrum", "artist": "Koloman Moser"},
            {"title": "Cottonwood Trees", "artist": "Gustave Baumann", "sources": ["smithsonian", "wikimedia"]},
            {"title": "Provincetown", "artist": "Gustave Baumann", "sources": ["smithsonian", "wikimedia"]},
        ],
    },
    {
        "id": "cartography",
        "title": "Maps & Cartography",
        "description": "The art of the map — gilded old-world atlases, decorative city views, and celestial charts.",
        "license": "Public Domain",
        "sources": ["wikimedia"],
        "pick_sources": ["wikimedia"],
        "queries": [],
        "query_supplement": False,
        "target": 26,
        "picks": [
            {"title": "Typus Orbis Terrarum", "artist": "Abraham Ortelius"},
            {"title": "Nova et Aucta Orbis Terrae Descriptio", "artist": "Gerardus Mercator"},
            {"title": "Universalis Cosmographia", "artist": "Martin Waldseemüller", "sources": ["wikimedia"]},
            {"title": "Nova Totius Terrarum Orbis Geographica", "artist": "Willem Blaeu"},
            {"title": "Americae Nova Tabula", "artist": "Willem Blaeu"},
            {"title": "Fra Mauro map", "artist": "Fra Mauro"},
            {"title": "Tabula Rogeriana", "artist": "Muhammad al-Idrisi"},
            {"title": "Leo Belgicus", "artist": "Claes Janszoon Visscher"},
            {"title": "Ptolemy world map", "artist": "Claudius Ptolemy"},
            {"title": "Harmonia Macrocosmica: Planisphaerium Copernicanum", "artist": "Andreas Cellarius"},
            {"title": "Harmonia Macrocosmica: Planisphaerium Ptolemaicum", "artist": "Andreas Cellarius"},
            {"title": "Harmonia Macrocosmica: Northern Constellations", "artist": "Andreas Cellarius"},
            {"title": "Uranometria: Orion", "artist": "Johann Bayer"},
            {"title": "Firmamentum Sobiescianum", "artist": "Johannes Hevelius"},
            {"title": "Atlas Coelestis", "artist": "John Flamsteed"},
            {"title": "Civitates Orbis Terrarum: Venice", "artist": "Braun and Hogenberg"},
            {"title": "Civitates Orbis Terrarum: Constantinople", "artist": "Braun and Hogenberg"},
            {"title": "Carta Marina", "artist": "Olaus Magnus"},
            {"title": "A New and Accurate Map of the World", "artist": "John Speed"},
            {"title": "Nova Belgica et Anglia Nova", "artist": "Willem Blaeu"},
            {"title": "Asiae Nova Descriptio", "artist": "Abraham Ortelius"},
        ],
    },
    {
        "id": "ancient-egypt",
        "title": "Ancient Egypt & the Near East",
        "description": "Treasures of the Nile and Mesopotamia — gold, stone, and hieroglyph across five thousand years.",
        "license": "Public Domain",
        "sources": ["met", "cleveland"],
        "pick_sources": ["museums", "wikimedia", "smithsonian"],
        "queries": [],
        "query_supplement": False,
        "target": 26,
        "picks": [
            {"title": "Mask of Tutankhamun", "artist": "Ancient Egyptian", "sources": ["wikimedia"]},
            {"title": "Narmer Palette", "artist": "Ancient Egyptian", "sources": ["wikimedia"]},
            {"title": "Great Sphinx of Giza", "artist": "Ancient Egyptian", "sources": ["wikimedia"]},
            {"title": "Rosetta Stone", "artist": "Ancient Egyptian", "sources": ["wikimedia"]},
            {"title": "Book of the Dead of Hunefer", "artist": "Ancient Egyptian", "sources": ["wikimedia"]},
            {"title": "Papyrus of Ani", "artist": "Ancient Egyptian", "sources": ["wikimedia"]},
            {"title": "Statue of Khafre Enthroned", "artist": "Ancient Egyptian", "sources": ["wikimedia"]},
            {"title": "Seated Scribe", "artist": "Ancient Egyptian", "sources": ["wikimedia"]},
            {"title": "Hippopotamus (William)", "artist": "Ancient Egyptian"},
            {"title": "Temple of Dendur", "artist": "Ancient Egyptian"},
            {"title": "Fayum Mummy Portrait of a Young Woman", "artist": "Romano-Egyptian"},
            {"title": "Faience Sphinx of Amenhotep III", "artist": "Ancient Egyptian"},
            {"title": "Canopic Jar with Falcon Head", "artist": "Ancient Egyptian"},
            {"title": "Statuette of the God Amun", "artist": "Ancient Egyptian"},
            {"title": "Wall Painting from the Tomb of Nebamun", "artist": "Ancient Egyptian", "sources": ["wikimedia"]},
            {"title": "Bust of Queen Tiye", "artist": "Ancient Egyptian", "sources": ["wikimedia"]},
            {"title": "Standard of Ur", "artist": "Sumerian", "sources": ["wikimedia"]},
            {"title": "Code of Hammurabi Stele", "artist": "Babylonian", "sources": ["wikimedia"]},
            {"title": "Human-Headed Winged Lion (Lamassu)", "artist": "Assyrian"},
            {"title": "Lion Hunt of Ashurbanipal", "artist": "Assyrian", "sources": ["wikimedia"]},
            {"title": "Striding Lion Glazed Brick Panel", "artist": "Babylonian"},
            {"title": "Statuette of Gudea", "artist": "Sumerian"},
            {"title": "Head of a Ruler", "artist": "Mesopotamian"},
            {"title": "Relief of a Winged Genius", "artist": "Assyrian"},
        ],
    },
    {
        "id": "asian-art",
        "title": "Asian Art Beyond Ukiyo-e",
        "description": "Chinese, Korean, Persian, and Indian masterworks of brush, ink, and gold across a thousand years.",
        "license": "Public Domain",
        "sources": ["met", "cleveland"],
        "pick_sources": ["museums", "wikimedia"],
        "queries": [],
        "query_supplement": False,
        "target": 26,
        "picks": [
            {"title": "Along the River During the Qingming Festival", "artist": "Zhang Zeduan", "sources": ["wikimedia"]},
            {"title": "Travelers Among Mountains and Streams", "artist": "Fan Kuan", "sources": ["wikimedia"]},
            {"title": "A Thousand Li of Rivers and Mountains", "artist": "Wang Ximeng", "sources": ["wikimedia"]},
            {"title": "Early Spring", "artist": "Guo Xi", "sources": ["wikimedia"]},
            {"title": "Nine Dragons", "artist": "Chen Rong", "sources": ["wikimedia"]},
            {"title": "Admonitions of the Instructress to the Court Ladies", "artist": "Gu Kaizhi", "sources": ["wikimedia"]},
            {"title": "Night Revels of Han Xizai", "artist": "Gu Hongzhong", "sources": ["wikimedia"]},
            {"title": "Finches and Bamboo", "artist": "Emperor Huizong"},
            {"title": "Old Trees, Level Distance", "artist": "Guo Xi"},
            {"title": "Summer Mountains", "artist": "Qu Ding"},
            {"title": "Diamond Mountains", "artist": "Jeong Seon", "sources": ["wikimedia"]},
            {"title": "The Court of Gayumars", "artist": "Sultan Muhammad", "sources": ["wikimedia"]},
            {"title": "Folio from the Shahnameh of Shah Tahmasp", "artist": "Persian (Safavid)"},
            {"title": "Akbar Restrains the Enraged Elephant", "artist": "Basawan", "sources": ["wikimedia"]},
            {"title": "Folio from the Hamzanama", "artist": "Mughal"},
            {"title": "Krishna Lifts Mount Govardhan", "artist": "Indian (Pahari)"},
            {"title": "Todi Ragini", "artist": "Indian (Rajput)"},
            {"title": "Pine Trees Screen", "artist": "Hasegawa Tōhaku", "sources": ["wikimedia"]},
            {"title": "Wind God and Thunder God", "artist": "Tawaraya Sōtatsu", "sources": ["wikimedia"]},
            {"title": "Red and White Plum Blossoms", "artist": "Ogata Kōrin", "sources": ["wikimedia"]},
            {"title": "Irises Screen", "artist": "Ogata Kōrin", "sources": ["wikimedia"]},
            {"title": "The Tale of Genji", "artist": "Japanese (Heian)", "sources": ["wikimedia"]},
            {"title": "David Vases", "artist": "Chinese (Yuan)", "sources": ["wikimedia"]},
            {"title": "Water-Moon Avalokiteshvara", "artist": "Chinese (Liao)"},
        ],
    },
    {
        "id": "medieval-illuminated",
        "title": "Medieval & Illuminated",
        "description": "Gold-leaf devotion, manuscript marginalia, and the luminous glow of the Middle Ages.",
        "license": "Public Domain",
        "sources": ["met"],
        "pick_sources": ["museums", "wikimedia"],
        "queries": [],
        "query_supplement": False,
        "target": 26,
        "picks": [
            {"title": "Très Riches Heures du Duc de Berry: January", "artist": "Limbourg Brothers", "sources": ["wikimedia"]},
            {"title": "Très Riches Heures du Duc de Berry: February", "artist": "Limbourg Brothers", "sources": ["wikimedia"]},
            {"title": "Book of Kells: Chi Rho Page", "artist": "Insular", "sources": ["wikimedia"]},
            {"title": "Lindisfarne Gospels: Carpet Page", "artist": "Insular", "sources": ["wikimedia"]},
            {"title": "Bayeux Tapestry: Harold's Oath", "artist": "Anglo-Norman", "sources": ["wikimedia"]},
            {"title": "The Cloisters Apocalypse", "artist": "French"},
            {"title": "The Belles Heures of Jean de France", "artist": "Limbourg Brothers"},
            {"title": "The Unicorn Rests in a Garden", "artist": "Franco-Flemish"},
            {"title": "The Unicorn Is Found", "artist": "Franco-Flemish"},
            {"title": "The Lady and the Unicorn: À Mon Seul Désir", "artist": "Franco-Flemish", "sources": ["wikimedia"]},
            {"title": "The Wilton Diptych", "artist": "Anglo-French", "sources": ["wikimedia"]},
            {"title": "Ghent Altarpiece: Adoration of the Mystic Lamb", "artist": "Jan van Eyck", "sources": ["wikimedia"]},
            {"title": "Utrecht Psalter", "artist": "Carolingian", "sources": ["wikimedia"]},
            {"title": "Beatus of Liébana: World Map", "artist": "Mozarabic", "sources": ["wikimedia"]},
            {"title": "Morgan Crusader Bible", "artist": "French", "sources": ["wikimedia"]},
            {"title": "Codex Manesse", "artist": "German", "sources": ["wikimedia"]},
            {"title": "Maestà", "artist": "Duccio di Buoninsegna", "sources": ["wikimedia"]},
            {"title": "Scrovegni Chapel: Lamentation", "artist": "Giotto di Bondone", "sources": ["wikimedia"]},
            {"title": "Santa Trinita Maestà", "artist": "Cimabue", "sources": ["wikimedia"]},
            {"title": "Annunciation", "artist": "Simone Martini", "sources": ["wikimedia"]},
            {"title": "Annunciation", "artist": "Fra Angelico", "sources": ["wikimedia"]},
            {"title": "Blue Virgin Window, Chartres", "artist": "French", "sources": ["wikimedia"]},
            {"title": "Sainte-Chapelle Stained Glass", "artist": "French", "sources": ["wikimedia"]},
            {"title": "Reliquary Statue of Sainte Foy", "artist": "Romanesque", "sources": ["wikimedia"]},
        ],
    },
    {
        "id": "marine",
        "title": "Marine & the Sea",
        "description": "Ships, storms, and the sublime power of the ocean across the centuries.",
        "license": "Public Domain",
        "sources": ["met", "chicago", "cleveland"],
        "pick_sources": ["wikimedia", "museums"],
        "queries": ["Ivan Aivazovsky", "marine seascape painting"],
        "query_supplement": False,
        "target": 26,
        "picks": [
            {"title": "The Slave Ship", "artist": "J. M. W. Turner"},
            {"title": "Snow Storm: Steam-Boat off a Harbour's Mouth", "artist": "J. M. W. Turner"},
            {"title": "The Shipwreck", "artist": "J. M. W. Turner"},
            {"title": "Dutch Boats in a Gale", "artist": "J. M. W. Turner"},
            {"title": "Breezing Up (A Fair Wind)", "artist": "Winslow Homer"},
            {"title": "The Fog Warning", "artist": "Winslow Homer"},
            {"title": "Northeaster", "artist": "Winslow Homer"},
            {"title": "Eight Bells", "artist": "Winslow Homer"},
            {"title": "The Ninth Wave", "artist": "Ivan Aivazovsky"},
            {"title": "The Black Sea", "artist": "Ivan Aivazovsky"},
            {"title": "Among the Waves", "artist": "Ivan Aivazovsky"},
            {"title": "A Dutch Ship in a Strong Breeze", "artist": "Willem van de Velde the Younger"},
            {"title": "Ships in a Stormy Sea", "artist": "Ludolf Bakhuizen"},
            {"title": "Ships in Distress off a Rocky Coast", "artist": "Ludolf Bakhuizen"},
            {"title": "The Monk by the Sea", "artist": "Caspar David Friedrich"},
            {"title": "The Stormy Sea", "artist": "Gustave Courbet"},
            {"title": "Calm Sea", "artist": "Gustave Courbet"},
            {"title": "Brig upon the Water", "artist": "Gustave Le Gray"},
            {"title": "The Great Wave, Sète", "artist": "Gustave Le Gray"},
            {"title": "A Dutch Yacht and Other Vessels Becalmed", "artist": "Jan van de Cappelle"},
            {"title": "Ships in a Storm", "artist": "Hendrick Dubbels"},
            {"title": "The Icebergs", "artist": "Frederic Edwin Church"},
        ],
    },
]


def get_collection(collection_id: str):
    return next((c for c in COLLECTIONS if c["id"] == collection_id), None)


# --------------------------------------------------------------------------- medium / kind
# The structured medium the free-text `medium` field lacks (~51% coverage). Collections are
# homogeneous by type, so a per-collection `kind` is a reliable, deterministic signal. This drives the
# paintings-only "Masterpieces" first-glimpse (CURATION-v2 / ADR-039): only PAINTERLY_KINDS are eligible
# for it, which excludes the high-fame NON-paintings (sculpture, photography, posters, space imagery,
# artifacts, maps, illuminated manuscripts) that otherwise dominate a purely fame-ranked first glance.
PAINTERLY_KINDS = {"painting", "print"}

COLLECTION_KIND = {
    "impressionism": "painting",
    "post-impressionism": "painting",
    "dutch-golden-age": "painting",
    "renaissance": "painting",
    "romanticism": "painting",
    "american-art": "painting",
    "portraits": "painting",
    "still-life": "painting",
    "modern-masters": "painting",
    "baroque": "painting",
    "symbolism-romance": "painting",
    "asian-art": "painting",
    "marine": "painting",
    "ukiyo-e": "print",           # fine-art woodblock prints (the Great Wave) — painterly, INCLUDED
    "botanical": "print",         # Audubon/Redouté prints & plates — painterly, low fame
    "sculpture-antiquity": "sculpture",
    "documentary-photography": "photo",
    "vintage-posters": "poster",
    "art-nouveau-decorative": "decorative",
    "cosmos": "space",
    "earth-and-spaceflight": "space",
    "ancient-egypt": "artifact",
    "cartography": "map",
    "medieval-illuminated": "illumination",
}

assert set(COLLECTION_KIND) == {c["id"] for c in COLLECTIONS}, \
    "COLLECTION_KIND must cover exactly the defined collections (guard against drift)"


def kind_for(collection_id: str) -> str:
    """Structured medium for a collection id ('painting' | 'print' | 'sculpture' | ...); '' if unknown."""
    return COLLECTION_KIND.get(collection_id, "")
